import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UIProvider } from "@/contexts/UIContext";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider";
import { CartProvider } from "@/contexts/CartContext";
import { UserProvider } from "@/contexts/UserContext";
import Header from "../components/Header"
import { Righteous } from 'next/font/google'
import { Footer } from "@/components/Footer";
import { ClerkTokenLogger } from "@/components/ClerkTokenLogger";
const _righteous = Righteous({ subsets: ["latin"], weight: "400" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${_righteous} antialiased`}
        >
          <QueryProvider>
            <UIProvider>
            <CartProvider>
              <UserProvider>
                <ClerkTokenLogger />
                <Header/>
                {children}
                <Footer/>
              </UserProvider>
            </CartProvider>
            </UIProvider>
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
