import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import Header from "../components/Header"
import { Righteous } from 'next/font/google'
import { Footer } from "@/components/Footer";
const _righteous = Righteous({ subsets: ["latin"], weight: "400" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${_righteous} ${_righteous} antialiased`}
      >
        <QueryProvider>
          <Header/>
          {children}
          <Footer/>
        </QueryProvider>
      </body>
    </html>
  );
}
